config/routes.rb
Rails.application.routes.draw do
  resources :wxinfos
  mount WeixinRailsMiddleware::Engine, at: "/"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/wxinfo.rb
class Wxinfo
  include Mongoid::Document
  include Mongoid::Timestamps
  field :appid, type: String
  field :appsecret, type: String
  field :secret_key, type: String
  field :token, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/wxinfos_controller.rb
class WxinfosController < ApplicationController
  before_action :set_wxinfo, only: [:show, :edit, :update, :destroy]

  # GET /wxinfos
  # GET /wxinfos.json
  def index
    @wxinfos = Wxinfo.all
  end

  # GET /wxinfos/1
  # GET /wxinfos/1.json
  def show
  end

  # GET /wxinfos/new
  def new
    @wxinfo = Wxinfo.new
  end

  # GET /wxinfos/1/edit
  def edit
  end

  # POST /wxinfos
  # POST /wxinfos.json
  def create
    @wxinfo = Wxinfo.new(wxinfo_params)

    respond_to do |format|
      if @wxinfo.save
        format.html { redirect_to @wxinfo, notice: 'Wxinfo was successfully created.' }
        format.json { render :show, status: :created, location: @wxinfo }
      else
        format.html { render :new }
        format.json { render json: @wxinfo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wxinfos/1
  # PATCH/PUT /wxinfos/1.json
  def update
    respond_to do |format|
      if @wxinfo.update(wxinfo_params)
        format.html { redirect_to @wxinfo, notice: 'Wxinfo was successfully updated.' }
        format.json { render :show, status: :ok, location: @wxinfo }
      else
        format.html { render :edit }
        format.json { render json: @wxinfo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wxinfos/1
  # DELETE /wxinfos/1.json
  def destroy
    @wxinfo.destroy
    respond_to do |format|
      format.html { redirect_to wxinfos_url, notice: 'Wxinfo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wxinfo
      @wxinfo = Wxinfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wxinfo_params
      params.require(:wxinfo).permit(:appid, :appsecret, :secret_key, :token)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wxinfos_helper.rb
module WxinfosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeixinTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/wxinfos/_form.html.erb
<%= form_with(model: wxinfo, local: true) do |form| %>
  <% if wxinfo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wxinfo.errors.count, "error") %> prohibited this wxinfo from being saved:</h2>

      <ul>
      <% wxinfo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :appid %>
    <%= form.text_field :appid, id: :wxinfo_appid %>
  </div>

  <div class="field">
    <%= form.label :appsecret %>
    <%= form.text_field :appsecret, id: :wxinfo_appsecret %>
  </div>

  <div class="field">
    <%= form.label :secret_key %>
    <%= form.text_field :secret_key, id: :wxinfo_secret_key %>
  </div>

  <div class="field">
    <%= form.label :token %>
    <%= form.text_field :token, id: :wxinfo_token %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wxinfos/edit.html.erb
<h1>Editing Wxinfo</h1>

<%= render 'form', wxinfo: @wxinfo %>

<%= link_to 'Show', @wxinfo %> |
<%= link_to 'Back', wxinfos_path %>

app/views/wxinfos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wxinfos</h1>

<table>
  <thead>
    <tr>
      <th>Appid</th>
      <th>Appsecret</th>
      <th>Secret key</th>
      <th>Token</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wxinfos.each do |wxinfo| %>
      <tr>
        <td><%= wxinfo.appid %></td>
        <td><%= wxinfo.appsecret %></td>
        <td><%= wxinfo.secret_key %></td>
        <td><%= wxinfo.token %></td>
        <td><%= link_to 'Show', wxinfo %></td>
        <td><%= link_to 'Edit', edit_wxinfo_path(wxinfo) %></td>
        <td><%= link_to 'Destroy', wxinfo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wxinfo', new_wxinfo_path %>

app/views/wxinfos/new.html.erb
<h1>New Wxinfo</h1>

<%= render 'form', wxinfo: @wxinfo %>

<%= link_to 'Back', wxinfos_path %>

app/views/wxinfos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Appid:</strong>
  <%= @wxinfo.appid %>
</p>

<p>
  <strong>Appsecret:</strong>
  <%= @wxinfo.appsecret %>
</p>

<p>
  <strong>Secret key:</strong>
  <%= @wxinfo.secret_key %>
</p>

<p>
  <strong>Token:</strong>
  <%= @wxinfo.token %>
</p>

<%= link_to 'Edit', edit_wxinfo_path(@wxinfo) %> |
<%= link_to 'Back', wxinfos_path %>